### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by ghost** [DAVFoundation/dav-cli#28]
Hi,
I just installed dav-cli. There are some deprecated packages. Should we do something about this?

```
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

```
Also, there are a lot of warnings regarding unused packages

**Comment by srfrnk** [comment]
Hey @gabimoncha - could be a great idea to handle these! Thanks :+1:

**Comment by sblasa** [comment]
@srfrnk and @gabimoncha -- If you update to the latest Node version, it fixes those errors on the Mac. I just tested it out for a different issue, and saw those warnings initially before I updated Node.
Hope that helps! :smile:

--Sussette

**Comment by TalAter** [comment]
Thanks @sblasa

**Comment by debragail** [comment]
@TalAter can we spec out what the recommended node version is for stable build?

**Comment by debragail** [comment]
@sblasa what version of node did you use?  I'm using 10.4.0 and i'm still getting the vulnerability.

```Debras-MacBook-Pro:dav-cli 0PHE1IA$ nvm use 10
Now using node v10.4.0 (npm v6.1.0)
Debras-MacBook-Pro:dav-cli 0PHE1IA$ npm install -g dav-cli
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
/Users/0PHE1IA/.nvm/versions/node/v10.4.0/bin/dav-cli -> /Users/0PHE1IA/.nvm/versions/node/v10.4.0/lib/node_modules/dav-cli/bin/dav-cli.js
+ dav-cli@0.3.0
removed 3 packages and updated 3 packages in 22.044s
Debras-MacBook-Pro:dav-cli 0PHE1IA$ node -v
v10.4.0

**Comment by TalAter** [comment]
From looking at these it seems like these deprecation messages are for **npm packages** which have been deprecated, and not specific to a certain node version or another.

The above warnings are triggered because both packages are marked as deprecated in npm:
* https://www.npmjs.com/package/tar.gz
* https://www.npmjs.com/package/fs-promise

Furthermore, the dependency on these packages are not defined by `dav-cli` itself, but rather by two of its dependencies' own dependencies... meaning the way to fix it would be to either stop using our own dependency (not an option), or having those dependencies fix their own issues.

<img width="715" alt="1__tal_tals-macbook-pro-5____dropbox_mysite_dav_dav-cli__zsh_" src="https://user-images.githubusercontent.com/926653/49427009-e1d2f500-f7aa-11e8-97be-09a5eab2dfa0.png">

Either way, it is out of our hands at the moment as far as I can see.

**Comment by sblasa** [comment]
@debragail I used 9.3.0. That was the last time I had updated node on my Mac. 

sblasa$ node --version
v9.3.0
